# Generated by Django 6.0.5 on 2026-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Game', 'Game')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('On-Hold', 'On-Hold')], default='Active', max_length=20)),
                ('current_progress', models.IntegerField(default=0)),
                ('total_progress', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
