# Generated by Django 6.0.5 on 2026-05-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_mediaitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
